#!/usr/bin/env python3
"""Create a dependency-free Manifest V3 starting project in Addonry generated output."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
from datetime import UTC, datetime
from pathlib import Path

from generate_icons import generate_icons

DEFAULT_OUTPUT_ROOT = Path(r"C:\Users\Julius\source\repos\Addonry\generated")
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def resolve_output_root(explicit: Path | None) -> Path:
    if explicit is not None:
        return explicit.expanduser().resolve()
    configured = os.environ.get("ADDONRY_OUTPUT_ROOT")
    return Path(configured).expanduser().resolve() if configured else DEFAULT_OUTPUT_ROOT


def scaffold(slug: str, name: str, description: str, output_root: Path, color: str = "#7C3AED") -> Path:
    if not SLUG_RE.fullmatch(slug):
        raise ValueError("slug must use lower-case letters, digits, and single hyphens")
    if not name.strip() or not description.strip():
        raise ValueError("name and description are required")

    output_root = output_root.expanduser().resolve()
    target = (output_root / slug).resolve()
    if target.parent != output_root:
        raise ValueError("resolved target escaped output root")
    if target.exists():
        raise FileExistsError(f"target already exists: {target}")

    source_dir = target / "src"
    tests_dir = target / "tests"
    metadata_dir = target / ".addonry"
    for directory in (source_dir, tests_dir, metadata_dir):
        directory.mkdir(parents=True, exist_ok=False)

    starter = Path(__file__).resolve().parent.parent / "assets" / "starter"
    for source_name, destination_name in (
        ("popup.html", "popup.html"),
        ("popup.css", "popup.css"),
        ("popup.js", "popup.js"),
        ("service-worker.js", "service-worker.js"),
    ):
        text = (starter / source_name).read_text(encoding="utf-8").replace("__EXTENSION_NAME__", name)
        (source_dir / destination_name).write_text(text, encoding="utf-8", newline="\n")
    shutil.copyfile(starter / "e2e.cjs", tests_dir / "e2e.cjs")

    icon_paths = generate_icons(target / "icons", color)
    icons = {str(size): f"icons/icon{size}.png" for size in (16, 32, 48, 128)}
    manifest = {
        "manifest_version": 3,
        "name": name,
        "version": "0.1.0",
        "description": description,
        "icons": icons,
        "action": {
            "default_title": name,
            "default_popup": "src/popup.html",
            "default_icon": icons,
        },
        "background": {"service_worker": "src/service-worker.js"},
    }
    (target / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")

    project = {
        "schemaVersion": 1,
        "slug": slug,
        "name": name,
        "createdAt": datetime.now(UTC).isoformat(),
        "status": "scaffolded",
        "acceptance": {},
        "architecture": {"manifestVersion": 3, "buildStep": False},
        "permissions": [],
        "verification": {},
        "installation": {"status": "not-installed"},
    }
    (metadata_dir / "project.json").write_text(json.dumps(project, indent=2) + "\n", encoding="utf-8", newline="\n")

    readme = f"""# {name}

{description}

Personal unpacked Chrome extension generated by Addonry. This directory is intentionally ignored by Addonry Git history.

## Load locally

1. Open `chrome://extensions`.
2. Enable Developer Mode.
3. Select **Load unpacked** and choose this directory.

## Verify

Run Addonry static validator and tailored real-Chrome E2E scenario before use.
"""
    (target / "README.md").write_text(readme, encoding="utf-8", newline="\n")

    if len(icon_paths) != 4:
        raise RuntimeError("icon generation did not produce expected files")
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--slug", required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--description", required=True)
    parser.add_argument("--output-root", type=Path)
    parser.add_argument("--color", default="#7C3AED")
    args = parser.parse_args()

    try:
        target = scaffold(
            args.slug,
            args.name,
            args.description,
            resolve_output_root(args.output_root),
            args.color,
        )
    except (ValueError, FileExistsError, OSError) as error:
        parser.error(str(error))
    print(json.dumps({"status": "created", "path": str(target)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
